# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ace908d9c2dcf9b8d4ef703e993e6008d783a22e1d92b5f0ccd934c29c671529a010643c8fd183bbce3d5081c35ea685e208ab61c9c7ba9ed240562b2b59151d

test:
  secret_key_base: 6d3e0f943b793792db49a3c20724fd129feac0ce5ef4dc9c2c46544c71a88f18a8f321022f4d019f8dfe2b8d54a49909e6dba54826686c966723d4fd3075a2a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
